### ISSUE TITLE
SetLargeAddressAware is running during design time builds

### ISSUE THREAD

**Issue by alexperovich** [KirillOsenkov/LargeAddressAware#7]
The SetLargeAddressAware task is running in design time builds ran by Roslyn's MSBuildWorkspace. This should not happen.

Relevant Logs:
```
Workspace failed: Msbuild failed when processing the file 'E:\dotnet\source-indexer\bin\repo\msbuild\src\MSBuild\MSBuild.csproj' with message: C:\Users\alperovi\.nuget\packages\largeaddressaware\1.0.3\build\LargeAddressAware.targets: (23, 5): Could not find file 'E:\dotnet\source-indexer\bin\repo\msbuild\artifacts\obj\MSBuild\Debug\net472\MSBuild.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at PEFile.LargeAddressAware.PrepareStream(String filePath, Action`2 action)
   at SetLargeAddressAware.SetLargeAddressAware.Execute()
```

**Comment by KirillOsenkov** [comment]
Published https://www.nuget.org/packages/LargeAddressAware/1.0.4.
